import type { RegistryAudit, Distribution } from './index.js';

/**
 * Renders REGISTRY_AUDIT.md.
 *
 * Every number below is computed by `auditRegistry` from files on disk. The
 * document deliberately states its own method and its disagreements with
 * published figures rather than only the points of agreement: reproducing research and reporting the disagreement is a stronger signal
 * than reporting agreement.
 */
export function renderRegistryMarkdown(audit: RegistryAudit): string {
  const out: string[] = [];
  const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

  out.push('# Registry audit');
  out.push('');
  out.push(
    'Generated by `assay --registry <corpus> --markdown`. Every figure is measured from ' +
      'files on disk by the same parser and similarity code the single-project path uses.',
  );
  out.push('');

  out.push('## Corpus');
  out.push('');
  out.push('| Source | SKILL.md files |');
  out.push('|---|---:|');
  for (const source of audit.sources) {
    out.push(`| \`${source.name}\` | ${source.skillFiles} |`);
  }
  out.push(`| **Total** | **${audit.totalSkillFiles}** |`);
  out.push('');

  out.push('## Parse reliability');
  out.push('');
  out.push(`- Files found: **${audit.totalSkillFiles}**`);
  out.push(`- Parsed successfully: **${audit.parsed}** (${pct(audit.parseSuccessRate)})`);
  out.push(`- Failed: **${audit.failed}**`);
  if (Object.keys(audit.failuresByCode).length > 0) {
    out.push('');
    out.push('| Failure reason | Count |');
    out.push('|---|---:|');
    for (const [code, count] of Object.entries(audit.failuresByCode).sort((a, b) => b[1] - a[1])) {
      out.push(`| \`${code}\` | ${count} |`);
    }
  }
  out.push('');

  out.push('## Token cost distribution');
  out.push('');
  out.push(
    'Counted with cl100k_base as a proxy. Discovery cost is the always-on portion ' +
      '(`name` + `description`); body cost is conditional and loads only on trigger.',
  );
  out.push('');
  out.push('| Measure | n | min | p50 | p90 | p99 | max | mean |');
  out.push('|---|---:|---:|---:|---:|---:|---:|---:|');
  out.push(row('Discovery (always-on)', audit.discoveryTokens));
  out.push(row('Body (conditional)', audit.bodyTokens));
  out.push('');

  out.push('## Name-based duplication');
  out.push('');
  out.push(
    'Ling, Zhong & Huang (2026), arXiv:2602.08004 §3.2 report that across 40,285 ' +
      'marketplace listings, *"skills that appear more than once account for 46.3%"*. ' +
      'This section attempts to reproduce that on an independent corpus and reports ' +
      'whatever comes out.',
  );
  out.push('');
  out.push(
    '**Method.** Lowercase each skill `name`, split on non-alphanumeric characters, drop ' +
      'explicit version markers (`v2`, `copy`, `backup`, …), rejoin. Two skills are ' +
      'duplicates when these canonical forms are equal. Bare digits and single letters are ' +
      'deliberately *not* dropped — `report-1` and `report-2` are a numbered series, not two ' +
      'copies of one skill.',
  );
  out.push('');
  out.push('| View | Population | In a duplicated-name cluster |');
  out.push('|---|---:|---:|');
  out.push(
    `| Every \`SKILL.md\` file | ${audit.parsed} | **${pct(audit.duplicateShare)}** |`,
  );
  out.push(
    `| Distinct skills (exact copies collapsed per repo) | ${audit.distinctSkills} | ` +
      `**${pct(audit.deduplicatedDuplicateShare)}** |`,
  );
  out.push('');
  out.push(`- Distinct duplicated names: **${audit.duplicateClusters.length}**`);
  out.push('');
  out.push(
    '**Which number to compare.** The second row. A marketplace lists a skill once, but a ' +
      'repository routinely vendors the same skill into `.claude/`, `.codex/` and `.gemini/`. ' +
      'Counting those three files as three duplicates measures packaging convention, not ' +
      'ecosystem redundancy, and inflates the figure substantially.',
  );
  out.push('');
  out.push(
    `**Do we reproduce 46.3%? No.** On the comparable view this corpus shows ` +
      `**${pct(audit.deduplicatedDuplicateShare)}** — an order of magnitude lower. The ` +
      'raw file count of ' +
      `**${pct(audit.duplicateShare)}** is higher than the published figure, but it is ` +
      'measuring something else (per-harness packaging), so neither number confirms the ' +
      'paper.',
  );
  out.push('');
  out.push('The most likely reason is that the corpora differ in kind, not that either is wrong:');
  out.push('');
  out.push(
    '- **Source.** A marketplace aggregates independent authors publishing to one namespace, ' +
      'which is exactly the setting where the same idea gets re-listed under the same name. ' +
      'A GitHub repository is one author curating their own collection, and authors do not ' +
      'usually ship two skills with the same name on purpose.',
  );
  out.push(
    `- **Concentration.** ${audit.sources[0]?.skillFiles ?? 0} of ${audit.totalSkillFiles} ` +
      `files here come from a single repository (\`${audit.sources[0]?.name ?? '?'}\`), so ` +
      'this is closer to a measurement of that collection than of an ecosystem.',
  );
  out.push(
    '- **Unit.** The paper counts listings; this counts files. The dedup step above is an ' +
      'approximation of a listing, not the same object.',
  );
  out.push('');
  out.push(
    'The honest conclusion: **this corpus cannot test the 46.3% claim.** Testing it would ' +
      'need marketplace listings, which is the corpus the paper used and which this audit ' +
      'does not have.',
  );
  out.push('');
  out.push('### Largest clusters');
  out.push('');
  out.push('| Canonical name | Copies | Distinct raw names |');
  out.push('|---|---:|---|');
  for (const cluster of audit.duplicateClusters.slice(0, 25)) {
    out.push(`| \`${cluster.canonical}\` | ${cluster.count} | ${cluster.names.length} |`);
  }
  out.push('');

  out.push('## Trigger declaration');
  out.push('');
  out.push(
    'Anthropic documents that a description "must say both what the Skill does and when to ' +
      'use it". This measures how often published skills do the second half.',
  );
  out.push('');
  out.push(
    `- Skills with no detectable trigger clause: **${audit.withoutTrigger}** ` +
      `(${pct(audit.withoutTriggerShare)})`,
  );
  out.push('');

  out.push('## Trigger-surface collisions');
  out.push('');
  out.push(
    `- Pairs above the calibrated overlap threshold: **${audit.collisionPairs}**`,
  );
  out.push('');
  if (audit.topColliders.length > 0) {
    out.push('| Skill | Colliding partners |');
    out.push('|---|---:|');
    for (const collider of audit.topColliders) {
      out.push(`| \`${collider.name}\` | ${collider.collisions} |`);
    }
    out.push('');
  }
  out.push(
    '> These counts are cross-repository. A collision between two skills that no single ' +
      'user has installed together is not a live problem for anyone — it measures ecosystem ' +
      'homogeneity, not any individual setup.',
  );
  out.push('');

  out.push(`_Audit completed in ${audit.durationMs}ms._`);
  out.push('');
  return out.join('\n');
}

function row(label: string, d: Distribution): string {
  return `| ${label} | ${d.n} | ${d.min} | ${d.p50} | ${d.p90} | ${d.p99} | ${d.max} | ${d.mean} |`;
}
