/**
 * Regenerates SELF_AUDIT.md.
 *
 * skillassay runs on its own repository, and the result is committed. If the
 * tool cannot produce a clean report on its own configuration, that is
 * disqualifying and must be fixed rather than excluded.
 *
 * Two directories are excluded, and the exclusion is printed in the output
 * rather than hidden here:
 *
 *   test/fixtures  — deliberately broken files whose entire purpose is to make
 *                    the analyzer report problems. Including them would fill the
 *                    self-audit with findings that are test data, which is what
 *                    the previous version of this file did.
 *   corpus         — third-party repositories fetched for validation; not part
 *                    of this project's own agent configuration.
 *
 * Usage: npm run self-audit
 */
import fs from 'node:fs';
import path from 'node:path';
import { analyze } from '../src/analyze/index.js';
import { renderTerminal } from '../src/report/terminal.js';
import { getRule } from '../src/rules/index.js';

const ROOT = path.resolve(import.meta.dirname, '..');
const EXCLUDED = ['test/fixtures', 'corpus', 'wild', 'ship'];

const result = analyze(ROOT, { exclude: EXCLUDED });

const lines: string[] = [];
lines.push('# Self-audit');
lines.push('');
lines.push(
  'skillassay analyzing its own repository. Regenerated by `npm run self-audit`; ' +
    'CI fails if the committed copy is out of date.',
);
lines.push('');
lines.push(`**Excluded from this audit:** ${EXCLUDED.map((e) => `\`${e}/\``).join(', ')}.`);
lines.push(
  '`test/fixtures/` contains intentionally broken files used to prove the analyzer ' +
    'detects problems; `corpus/` and `wild/` hold third-party repositories fetched for ' +
    'validation; `ship/` is a generated copy. None is part of this project\'s own agent ' +
    'configuration. Everything else in the repository is included.',
);
lines.push('');

lines.push('## Result');
lines.push('');
lines.push(`- Artifacts analyzed: **${result.artifacts.length}**`);
lines.push(`- Skills parsed: **${result.skills.length}**`);
lines.push(`- Files that failed to parse: **${result.errors.length}**`);
lines.push(
  `- Always-on context: **${result.budget.total.value} tokens** ` +
    `(${((result.budget.total.value / result.target.contextWindow) * 100).toFixed(2)}% of a ` +
    `${(result.target.contextWindow / 1000).toFixed(0)}K window)`,
);
lines.push(`- Findings: **${result.findings.length}**`);
lines.push('');

if (result.findings.length === 0 && result.errors.length === 0) {
  lines.push('**Clean.** No findings.');
} else {
  lines.push('| Severity | Rule | Location | Summary |');
  lines.push('|---|---|---|---|');
  for (const finding of result.findings) {
    const rule = getRule(finding.ruleId);
    const loc = finding.locations
      .map((l) => `\`${l.path}${l.line === undefined ? '' : `:${l.line}`}\``)
      .join('<br>');
    lines.push(`| ${finding.severity} | \`${finding.ruleId}\` (${rule.title}) | ${loc} | ${finding.summary} |`);
  }
  for (const error of result.errors) {
    lines.push(`| error | parse | \`${error.relPath}\` | ${error.code}: ${error.message} |`);
  }
}
lines.push('');

lines.push('## Budget attribution');
lines.push('');
lines.push('| Tokens | Artifact | Portion |');
lines.push('|---:|---|---|');
for (const line of result.budget.lines) {
  lines.push(`| ${line.tokens.value} | \`${line.relPath}\` | ${line.portion} |`);
}
lines.push('');

if (result.budget.unmeasured.length > 0) {
  lines.push('## Known unmeasured cost');
  lines.push('');
  for (const item of result.budget.unmeasured) {
    lines.push(`- \`${item.source}\` — ${item.reason}`);
  }
  lines.push('');
}

lines.push('## Terminal output');
lines.push('');
lines.push('```');
lines.push(renderTerminal(result, { color: false, verbose: false }).trimEnd());
lines.push('```');
lines.push('');

fs.writeFileSync(path.join(ROOT, 'SELF_AUDIT.md'), `${lines.join('\n')}\n`);

console.log(
  `SELF_AUDIT.md written: ${result.findings.length} finding(s), ` +
    `${result.errors.length} parse error(s), ${result.budget.total.value} always-on tokens.`,
);

// A non-clean self-audit is a real signal, so make it visible in CI output.
if (result.findings.length > 0 || result.errors.length > 0) {
  console.error('\nSelf-audit is NOT clean. Fix the findings above rather than excluding them.');
  process.exit(1);
}
